ebean:
  ddl:
    generate: true  # Отключаем автогенерацию DDL
    run: true

datasource:
  db:
    username: postgres
    password: 0031
    url: jdbc:postgresql://localhost:5432/stud36x
    driver: org.postgresql.Driver